server:
    port: 9002

spring:
    application:
        name: PLAYER-SERVICE



eureka:
    client:
        register-with-eureka: true
        fetch_registry: true
        service-url:
            defaultZone:  http://localhost:8761/eureka/
    instance:
        hostname: localhost